/*
 * This source file was generated by the Gradle 'init' task
 */
package org.opendcs;

import org.gradle.api.Project;
import org.gradle.api.artifacts.repositories.ArtifactRepository;
import org.gradle.api.artifacts.repositories.MavenArtifactRepository;
import org.gradle.api.publish.PublishingExtension;
import org.gradle.api.publish.maven.MavenPublication;
import org.gradle.api.tasks.bundling.Zip;

import org.gradle.api.Plugin;

/**
 * A simple 'hello world' plugin.
 */
public class MavenCentralUploadPlugin implements Plugin<Project> {
    private static final String GROUP = "Central API";
    private static final String PUBLISH_ALL_TASK = "publishAllToNewMavenCentralApi";
    private static final String CENTRAL_API_SUFFIX = "NewCentralApi";


    @Override
    public void apply(Project project)
    {
        project.getPluginManager().withPlugin("maven-publish", publishPlugin ->
        {
            final var hasSigning = project.getPluginManager().hasPlugin("signing");
            var tasks = project.getTasks();
            var projectName = Character.toTitleCase(project.getName().charAt(0)) + project.getName().substring(1);
            var extension = project.getExtensions().findByType(PublishingExtension.class);

            if (extension != null)
            {
                tasks.register(PUBLISH_ALL_TASK, task ->
                {
                    task.setGroup(GROUP);
                    task.setDescription("Publish all artifacts of this build to maven central.");
                });
                var assembleTask = tasks.register("assemble"+projectName+"CentralApiBundle", AssembleBundleTask.class, task ->
                {
                    task.outputDirectory.set(project.getLayout().getBuildDirectory().dir("bundle"));
                    task.setGroup(GROUP);
                    task.setDescription("Gather all the require artifacts for this project.");
                });
                extension.getPublications().withType(MavenPublication.class).all(pub ->
                {
                    final var name = pub.getName();
                    final var pubName = Character.toTitleCase(name.charAt(0)) + name.substring(1);
                    assembleTask.configure(task ->
                    {
                        task.publications.add(pub);
                        pub.getArtifacts().all(a -> task.dependsOn(a.getBuildDependencies()));
                        task.dependsOn(tasks.named("generatePomFileFor"+pubName+"Publication"));
                        if (hasSigning)
                        {
                            task.dependsOn(tasks.matching(t -> t.getName().equals("sign"+pubName+"Publication")));
                        }
                    });
                });
                    final var zipBundleTask = tasks.register("zip"+projectName+CENTRAL_API_SUFFIX+"Bundle", Zip.class, task ->
                    {
                        task.getInputs().dir(assembleTask.get().getOutputDirectory());
                        task.dependsOn(assembleTask);
                        task.setGroup(GROUP);
                        task.getArchiveBaseName().set("central-api-bundle-for-"+project.getName());
                        task.getDestinationDirectory().set(project.getLayout().getBuildDirectory());
                        task.from(assembleTask.get().getOutputs());
                        task.getOutputs().file(task.getArchiveFile());
                    });

                    final var publishTask = tasks.register("publish"+projectName+"To"+CENTRAL_API_SUFFIX, PublishToMavenCentral.class, task ->
                    {
                        var repos = extension.getRepositories();
                        final ArtifactRepository remote = repos.findByName("mavenCentralApi");
                        task.getInputs().file(zipBundleTask.get().getArchiveFile().get());
                        task.dependsOn(zipBundleTask);
                        task.remote = (MavenArtifactRepository)remote;
                        task.bundle.set(zipBundleTask.get().getArchiveFile());
                        task.getOutputs().upToDateWhen(t -> false);
                        task.setGroup(GROUP);
                        task.setDescription("Publish bundle to Maven Central API.");
                        task.doLast(s ->
                        {
                            System.out.println("Hello from plugin 'org.opendcs.maven-central-upload'");
                        });
                    });
                    tasks.named(PUBLISH_ALL_TASK, t -> t.dependsOn(publishTask));
                
            }
        });
    }
}
