/*
 * This source file was generated by the Gradle 'init' task
 */
package org.opendcs;

import org.gradle.api.Project;
import org.gradle.api.artifacts.repositories.ArtifactRepository;
import org.gradle.api.artifacts.repositories.MavenArtifactRepository;
import org.gradle.api.publish.PublishingExtension;
import org.gradle.api.publish.maven.tasks.PublishToMavenLocal;
import org.gradle.api.GradleException;
import org.gradle.api.Plugin;

/**
 * A simple 'hello world' plugin.
 */
public class MavenCentralUploadPlugin implements Plugin<Project> {
    @Override
    public void apply(Project project) {
        project.getPluginManager().withPlugin("maven-publish", publishPlugin ->
        {
            project.afterEvaluate(p ->
            {
                final var publishTasks = p.getTasks().withType(PublishToMavenLocal.class);
                var repos = p.getExtensions().getByType(PublishingExtension.class).getRepositories();

                final ArtifactRepository remote = repos.getAt("mavenCentralApi");
                final MavenArtifactRepository mavenLocal = repos.mavenLocal();

                p.getTasks().register("publishToMavenCentralApi", PublishToMavenCentral.class, task ->
                {
                    task.local = mavenLocal;
                    task.remote = (MavenArtifactRepository)remote;
                    task.setGroup("Publishing");
                    task.dependsOn(publishTasks);
                    task.doLast(s ->
                    {
                        System.out.println("Hello from plugin 'org.opendcs.maven-central-upload'");
                    });
               });
            });
            
        });
    }
}
