---
name: Release
on:
  workflow_call:
    inputs:
      branch:
       type: string
       required: true
    secrets:
      token:
       required: false
      signingKey:
        required: true
      signingKeyPassword:
        required: true
      mavenCentralUserName:
        required: true
      mavenCentralPassword:
        required: true
  workflow_dispatch:
    inputs:
      branch:
        type: choice
        required: true
        description: Which Branch to make the build from
        options:
          - develop
      
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{inputs.branch}}
      - name: setup java
        uses: actions/setup-java@v4.7.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Set version
        run: echo "VERSION=${{inputs.branch}}" >> $GITHUB_ENV
      - name: show version
        run: echo ${VERSION}
      - name: Push to central
        run: |
          # Build the plugin first, so it can publish itself.
          ./gradlew build -PversionOverride=$VERSION 
          ./gradlew publishAllToNewMavenCentralApi --info -Psign=true \
             -PversionOverride=$VERSION \
             -PsigningKeyPassword="${{ secrets.signingKeyPassword != null && secrets.signingKeyPassword || secrets.SIGNING_KEY_PASSWORD }}" \
             -PcentralApiUsername=${{ secrets.mavenCentralUsername != null && secrets.mavenCentralUsername || secrets.MAVENCENTRAL_USERNAME }} \
             -PcentralApiPassword=${{ secrets.mavenCentralPassword != null && secrets.mavenCentralPassword || secrets.MAVENCENTRAL_PASSWORD }} \
             -PsigningKey="${{ secrets.signingKey != null && secrets.signingKey || secrets.SIGNING_KEY }}"
             -PautomaticPublish=true