---
name: Tagged Release
on:
  push:
    tags:
      - '[0-9]*.[0-9]*.[0-9]*'
jobs:
  release:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/release.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      signingKey: ${{ secrets.SIGNING_KEY }}
      signingKeyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
      mavenCentralUsername: ${{ secrets.MAVENCENTRAL_USERNAME }}
      mavenCentralPassword: ${{ secrets.MAVENCENTRAL_PASSWORD }}
    with:
      branch: ${{github.ref_name}}